# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8430258ee89b1ec721bb907220c8ca7627658a98b57df13763f14e3668fb63af112ded8e27dfd6d9405ab5e7a26bdf8b57c731e42907098d41717c74250d88eb

test:
  secret_key_base: a4bdd7a9240e4e696ebc0081f77b0b83f20c7a3fc329bf1abd37266e3d1ecea0b69e7599b33414df35689f6e7367ffa565e4573799128f90e07b7ce3cb3bb669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
